import Head from 'next/head'
import { useCallback, useState } from 'react'
import FolderLister from '../components/FolderLister'
import FolderSelector from '../components/FolderSelector'
import styles from '../styles/Home.module.css'

const API_ENDPOINT = 'http://localhost:5000/api/listx'

export default function Home() {

  const [folderContent, setFolderContent] = useState([])

  const getFolderDir = useCallback(async (folder) => {
    if (!folder) {
      alert("Please enter a folder")
    }
    const response = await fetch(API_ENDPOINT + '?path=' + folder)
    const contents = await response.json()
    setFolderContent(contents)
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>ListX</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">ListX!</a>
        </h1>

        <div className={styles.folderSelector}>
          <FolderSelector onListContent={getFolderDir} />
        </div>
        <hr />
        <FolderLister folderList={folderContent} />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://casoetan.com"
          target="_blank"
          rel="noopener noreferrer"
        >
          Copyright CASoetan
        </a>
      </footer>
    </div>
  )
}
